plugins {
    id 'idea'
    id 'groovy'
}

repositories {
    mavenCentral()
}

ext {
    gebVersion = "7.0"
    seleniumVersion = "4.35.0" // latest 4.35.0
}

dependencies {

    // If using Spock, need to depend on geb-spock
    // testImplementation "org.gebish:geb-spock:${gebVersion}"
    testImplementation "org.apache.groovy.geb:geb-spock:${gebVersion}"
    testImplementation "org.spockframework:spock-core:2.3-groovy-4.0"

    // If using JUnit, need to depend on geb-junit (4 or 5)
    // testImplementation "org.gebish:geb-junit4:${gebVersion}"
    // testImplementation "junit:junit-dep:4.8.2"

    // Need a driver implementation
    testImplementation "org.seleniumhq.selenium:selenium-firefox-driver:${seleniumVersion}"
    testRuntimeOnly "org.seleniumhq.selenium:selenium-support:${seleniumVersion}"

    testImplementation 'org.testcontainers:selenium:1.21.3' // latest 1.21.3
    testImplementation "org.seleniumhq.selenium:selenium-remote-driver:${seleniumVersion}" // latest 4.35.0

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.13.4'

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

/*
test {
    systemProperties "geb.build.reportsDir": "$reportsDir/geb"
}
*/

tasks.withType(Test) {
    maxHeapSize = "1g"
    jvmArgs '-XX:MaxMetaspaceSize=128m'
    testLogging {
        exceptionFormat = 'full'
    }
    useJUnitPlatform()
}
